#define kp 0.01 // these values are generated by your matlab just plug in the values what you used there 
#define kd 0.005
#define ki 0



int l1,l2,c1,c2,r1,r2,n;
int position,error,previouserror=0,correction,derivative,integral=0;
const int maxspeed=250;// use value from matlab simulation



int pos() // this function deals with getting the input from line following sensor so
	 // the code within will be different for your project. I have just included it for reference
{
	l2=bit_is_set(PINA,1) >> 0;
	l1=bit_is_set(PINA,2) >> 1;
	c2=bit_is_set(PINA,3) >> 2;
	c1=bit_is_set(PINA,4) >> 3;
	r2=bit_is_set(PINA,5) >> 4;
	r1=bit_is_set(PINA,6) >> 5;
		
	n=l2+l1+c2+c1+r2+r1;
	return ((2*l2 + 3*l1 + 4*c2 + 5*c1 + 6*r2 + 7*r1)*1000)/n;
	
}


int PIDcontrol() // This id the PID control function you'll need this 
{
	position=pos();
	
	error=position- 4500;
		
	derivative=error-previouserror;
		
	integral+=error;
		
	previouserror=error;
		
	return ((error*kp)+(integral*ki)+(derivative*kd));
}


void set_motor(int a, int b) // this function is responsible to change the motor speed as per PID values.
// The contents will be different in your code.

//In this code ocr0 and ocr2 are responsible to generate pwm to change motor speed. 
{
	OCR0=a;
	OCR2=b;
}



int main(void)
// its the main function and its name may vary for your project but the things within while loop is needed for your project too 
{
	inicialize();
	
    while(1) // try to understand the working of code below for PID
    {
		correction=PIDcontrol();
		
		if (correction>maxspeed)
		{
			correction=maxspeed;
		}
		if (correction<-maxspeed)
		{
			correction= -maxspeed;
		}
		
		
		if (correction<0)
		{
			set_motor(maxspeed+correction,maxspeed);
		}
		else
		{
			set_motor(maxspeed,maxspeed-correction);
		}
		
		
    }
} 